using DynoTune.Models;
using System.Linq;

namespace DynoTune.Services;

public class AdaptiveOptimizationService
{
    private static readonly TimeSpan RecommendationCooldown = TimeSpan.FromSeconds(20);

    private readonly ProfileService _profileService;
    private readonly WindowsPowerPlanService _powerPlanService;
    private DateTime _lastRecommendationUtc = DateTime.MinValue;

    // Stable-workload tracking for auto-triggering profile search
    private WorkloadType _lastStableWorkloadType = WorkloadType.Unknown;
    private int _stableWorkloadTicks;
    private int _searchTriggerCooldownTicks;
    private const int StableWorkloadTicksRequired = 30;
    private const int SearchTriggerCooldownTicksTotal = 300;

    public AdaptiveOptimizationService(ProfileService profileService, WindowsPowerPlanService powerPlanService)
    {
        _profileService = profileService;
        _powerPlanService = powerPlanService;
    }

    public OptimizationSessionState SessionState { get; } = new();

    public void StartSession()
    {
        SessionState.IsRunning = true;
        SessionState.Phase = OptimizationPhase.BaselineCaptured;
        SessionState.BaselineProfileName = _profileService.GetVendorSafeBaselineProfile()?.Name ?? string.Empty;
        SessionState.LastDecision = "Optimization started in recommendation mode.";
        SessionState.AcceptedRecommendations = 0;
    }

    public void StopSession()
    {
        SessionState.IsRunning = false;
        SessionState.Phase = OptimizationPhase.Idle;
        SessionState.LastDecision = "Optimization stopped.";
        _stableWorkloadTicks = 0;
        _lastStableWorkloadType = WorkloadType.Unknown;
        SessionState.ShouldTriggerSearch = false;
    }

    /// <summary>
    /// Called by MainWindow after auto-triggering a search to reset the flag and start the cooldown.
    /// </summary>
    public void NotifySearchTriggered()
    {
        SessionState.ShouldTriggerSearch = false;
        _searchTriggerCooldownTicks = SearchTriggerCooldownTicksTotal;
    }

    public void Tick(SensorSnapshot snapshot, ClassificationResult classification,
                     DangerState dangerState, bool isSearchActive)
    {
        SessionState.ActiveWorkloadType = classification.WorkloadType;
        if (!SessionState.IsRunning)
        {
            return;
        }

        if (dangerState.Level == DangerLevel.Critical)
        {
            RollbackToVendorSafe($"Critical danger: {dangerState.Reason}");
            return;
        }

        // Track how long the current workload has been stable
        if (classification.WorkloadType == _lastStableWorkloadType)
        {
            _stableWorkloadTicks++;
        }
        else
        {
            _lastStableWorkloadType = classification.WorkloadType;
            _stableWorkloadTicks = 1;
            SessionState.ShouldTriggerSearch = false;
        }

        if (_searchTriggerCooldownTicks > 0)
            _searchTriggerCooldownTicks--;

        // Signal that a search is needed when conditions are met
        bool noProfileForWorkload = _profileService.Profiles.All(
            p => !p.IsAutoGenerated || p.TargetWorkloadType != classification.WorkloadType);

        SessionState.ShouldTriggerSearch =
            _stableWorkloadTicks >= StableWorkloadTicksRequired
            && noProfileForWorkload
            && dangerState.Level == DangerLevel.Safe
            && _searchTriggerCooldownTicks == 0;

        DateTime now = DateTime.UtcNow;
        if (now - _lastRecommendationUtc < RecommendationCooldown)
        {
            return;
        }

        SessionState.RecommendedCandidate = BuildCandidate(classification, snapshot);
        SessionState.Phase = OptimizationPhase.Recommending;
        _lastRecommendationUtc = now;
        SessionState.LastDecision = $"Recommended candidate: {SessionState.RecommendedCandidate.Name}";

        // Don't apply settings while profile search owns the hardware
        if (!isSearchActive &&
            SessionState.AutoApplyEnabled &&
            SessionState.AcceptedRecommendations >= SessionState.AutoApplyAfterAcceptedCount)
        {
            ApplyRecommendedCandidate();
        }
    }

    public bool ApplyRecommendedCandidate()
    {
        OptimizationCandidate? candidate = SessionState.RecommendedCandidate;
        if (candidate is null)
        {
            SessionState.LastDecision = "No recommended candidate available.";
            return false;
        }

        SessionState.Phase = OptimizationPhase.Applying;

        TuningProfile? profile = _profileService.Profiles.FirstOrDefault(p =>
            p.Name.Equals(candidate.ProfileName, StringComparison.OrdinalIgnoreCase));
        if (profile is null)
        {
            SessionState.LastResult = new OptimizationResult
            {
                CandidateName = candidate.Name,
                CandidateApplied = false,
                Accepted = false,
                AcceptanceReason = "Profile not found."
            };
            SessionState.LastDecision = "Candidate apply failed: profile missing.";
            SessionState.Phase = OptimizationPhase.Recommending;
            return false;
        }

        _profileService.SetActiveProfile(profile.Name);
        bool powerPlanApplied = _profileService.TryApplyPowerPlan(profile);

        bool accepted = powerPlanApplied;
        SessionState.LastResult = new OptimizationResult
        {
            CandidateName = candidate.Name,
            CandidateApplied = powerPlanApplied,
            Accepted = accepted,
            AcceptanceReason = accepted
                ? "Applied with safe policy. GPU candidate recorded for ADLX profile path."
                : "Windows power plan apply failed."
        };

        if (accepted)
        {
            SessionState.AcceptedRecommendations++;
            SessionState.Phase = OptimizationPhase.Monitoring;
            SessionState.LastDecision = $"Applied: {candidate.Name}";
        }
        else
        {
            SessionState.Phase = OptimizationPhase.Recommending;
            SessionState.LastDecision = $"Apply rejected: {candidate.Name}";
        }

        return accepted;
    }

    public void RollbackToVendorSafe(string reason)
    {
        TuningProfile fallback = _profileService.GetSafeFallbackProfile();
        bool applied = _profileService.TryApplyPowerPlan(fallback);
        SessionState.Phase = OptimizationPhase.RolledBack;
        SessionState.LastResult = new OptimizationResult
        {
            CandidateName = fallback.Name,
            CandidateApplied = applied,
            Accepted = false,
            AcceptanceReason = "Rollback executed.",
            RollbackReason = reason
        };
        SessionState.LastDecision = $"Rolled back to: {fallback.Name}";
    }

    private OptimizationCandidate BuildCandidate(ClassificationResult classification, SensorSnapshot snapshot)
    {
        TuningProfile selected = _profileService.SuggestProfile(classification) ??
                                _profileService.ActiveProfile ??
                                _profileService.GetSafeFallbackProfile();

        WindowsPowerPlanKind targetPlan = classification.WorkloadType switch
        {
            WorkloadType.Idle => WindowsPowerPlanKind.PowerSaver,
            WorkloadType.Browsing => WindowsPowerPlanKind.Balanced,
            WorkloadType.Office => WindowsPowerPlanKind.Balanced,
            WorkloadType.Media => WindowsPowerPlanKind.Balanced,
            WorkloadType.Gaming => WindowsPowerPlanKind.HighPerformance,
            WorkloadType.HeavyCompute => WindowsPowerPlanKind.HighPerformance,
            _ => selected.PreferredPowerPlan
        };

        return new OptimizationCandidate
        {
            Name = $"{classification.WorkloadType} candidate",
            ProfileName = selected.Name,
            WorkloadType = classification.WorkloadType,
            PreferredPowerPlan = targetPlan,
            GpuPowerLimitPercent = selected.GpuPowerLimitPercent,
            GpuMaxClockMHz = selected.GpuMaxClockMHz,
            GpuVoltageMv = selected.GpuVoltageMv,
            Reason = $"Rule-based recommendation from workload '{classification.WorkloadType}' and GPU load {snapshot.Gpu.UsagePercent:F0}%.",
            RecommendedAtUtc = DateTime.UtcNow
        };
    }
}
