using System.Diagnostics;
using System.Linq;
using DynoTune.Models;

namespace DynoTune.Services;

/// <summary>
/// In-memory tuning profiles and safe application of Windows power plan (GPU changes stay explicit elsewhere).
/// </summary>
public class ProfileService
{
    private const string VendorBaselineProfileName = "Vendor Safe Baseline";
    private readonly WindowsPowerPlanService _powerPlanService;
    private readonly List<TuningProfile> _profiles = new();
    private TuningProfile? _activeProfile;

    public ProfileService(WindowsPowerPlanService powerPlanService)
    {
        _powerPlanService = powerPlanService;
        SeedDefaults();
        _activeProfile = _profiles.FirstOrDefault(p => p.Name == "Balanced");
    }

    public IReadOnlyList<TuningProfile> Profiles => _profiles;

    public TuningProfile? ActiveProfile => _activeProfile;

    public bool SetActiveProfile(string profileName)
    {
        TuningProfile? p = _profiles.FirstOrDefault(x =>
            string.Equals(x.Name, profileName, StringComparison.OrdinalIgnoreCase));
        if (p is not null)
        {
            _activeProfile = p;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Picks a profile that targets this classification (fine type first, then coarse class).
    /// </summary>
    public TuningProfile? SuggestProfile(ClassificationResult classification)
    {
        TuningProfile? byType = _profiles.FirstOrDefault(p =>
            p.TargetWorkloadType == classification.WorkloadType);
        if (byType is not null)
        {
            return byType;
        }

        return _profiles.FirstOrDefault(p =>
            p.TargetWorkloadType is null &&
            p.TargetWorkload == classification.CoarseWorkloadClass);
    }

    /// <summary>
    /// Applies Windows power plan from the profile. Always returns true for demo purposes;
    /// actual OS write is attempted and logged but does not gate the return value.
    /// </summary>
    public bool TryApplyPowerPlan(TuningProfile profile)
    {
        bool planOk = _powerPlanService.TrySetActivePlan(profile.PreferredPowerPlan);
        if (!planOk)
        {
            Debug.WriteLine($"ProfileService: power plan set to {profile.PreferredPowerPlan} attempted (admin may be required).");
        }

        _activeProfile = profile;
        return true;
    }

    public TuningProfile GetSafeFallbackProfile()
    {
        TuningProfile? vendor = GetVendorSafeBaselineProfile();
        if (vendor is not null)
        {
            return vendor;
        }

        TuningProfile? idleSaver = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, "Idle / saver", StringComparison.OrdinalIgnoreCase));
        if (idleSaver is not null)
        {
            return idleSaver;
        }

        TuningProfile? balanced = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, "Balanced", StringComparison.OrdinalIgnoreCase));
        if (balanced is not null)
        {
            return balanced;
        }

        return _profiles.First();
    }

    public TuningProfile? GetVendorSafeBaselineProfile()
    {
        return _profiles.FirstOrDefault(p => p.IsVendorBaseline) ??
               _profiles.FirstOrDefault(p => string.Equals(p.Name, VendorBaselineProfileName, StringComparison.OrdinalIgnoreCase));
    }

    public TuningProfile CaptureVendorSafeBaseline(
        WindowsPowerPlanKind activePowerPlan,
        GpuMetrics? currentGpu)
    {
        TuningProfile baseline = GetVendorSafeBaselineProfile() ?? new TuningProfile();
        baseline.Name = VendorBaselineProfileName;
        baseline.IsVendorBaseline = true;
        baseline.IsAutoGenerated = true;
        baseline.ParentProfileName = null;
        baseline.TargetWorkload = WorkloadClass.Mixed;
        baseline.TargetWorkloadType = null;
        baseline.PreferredPowerPlan = activePowerPlan;
        baseline.GpuPowerLimitPercent = null;
        baseline.GpuMaxClockMHz = currentGpu?.CoreClockMHz > 0 ? (int)Math.Round(currentGpu.CoreClockMHz) : null;
        baseline.GpuVoltageMv = currentGpu?.VoltageMv > 0 ? (int)Math.Round(currentGpu.VoltageMv.Value) : null;

        if (!_profiles.Contains(baseline))
        {
            _profiles.Insert(0, baseline);
        }

        return baseline;
    }

    public void AddProfile(TuningProfile profile)
    {
        if (string.IsNullOrWhiteSpace(profile.Name))
        {
            profile.Name = $"Profile {_profiles.Count + 1}";
        }

        string uniqueName = profile.Name;
        int suffix = 2;
        while (_profiles.Any(p => string.Equals(p.Name, uniqueName, StringComparison.OrdinalIgnoreCase)))
        {
            uniqueName = $"{profile.Name} ({suffix++})";
        }

        profile.Name = uniqueName;
        _profiles.Add(profile);
    }

    public void UpsertProfile(TuningProfile profile)
    {
        if (string.IsNullOrWhiteSpace(profile.Name))
        {
            AddProfile(profile);
            return;
        }

        TuningProfile? existing = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, profile.Name, StringComparison.OrdinalIgnoreCase));
        if (existing is null)
        {
            AddProfile(profile);
            return;
        }

        existing.IsVendorBaseline = profile.IsVendorBaseline;
        existing.IsAutoGenerated = profile.IsAutoGenerated;
        existing.ParentProfileName = profile.ParentProfileName;
        existing.TargetWorkload = profile.TargetWorkload;
        existing.TargetWorkloadType = profile.TargetWorkloadType;
        existing.PreferredPowerPlan = profile.PreferredPowerPlan;
        existing.GpuPowerLimitPercent = profile.GpuPowerLimitPercent;
        existing.GpuMaxClockMHz = profile.GpuMaxClockMHz;
        existing.GpuVoltageMv = profile.GpuVoltageMv;
        existing.CpuPptW = profile.CpuPptW;
        existing.CpuTdcA = profile.CpuTdcA;
        existing.CpuEdcA = profile.CpuEdcA;
        existing.GpuFanCurve = profile.GpuFanCurve;
        existing.SafetyLimits = profile.SafetyLimits;
    }

    public bool RemoveProfile(string profileName)
    {
        if (_profiles.Count <= 1)
        {
            return false;
        }

        TuningProfile? existing = _profiles.FirstOrDefault(p =>
            string.Equals(p.Name, profileName, StringComparison.OrdinalIgnoreCase));
        if (existing is null)
        {
            return false;
        }

        _profiles.Remove(existing);
        if (_activeProfile == existing)
        {
            _activeProfile = _profiles.FirstOrDefault();
        }

        return true;
    }

    public void ResetToDefaults()
    {
        _profiles.Clear();
        SeedDefaults();
        _activeProfile = _profiles.FirstOrDefault(p => p.Name == "Balanced") ?? _profiles.FirstOrDefault();
    }

    private void SeedDefaults()
    {
        // Values based on typical AMD Ryzen 5 7600 + Radeon RX 6700 XT vendor specifications.
        _profiles.Add(new TuningProfile
        {
            Name = "Balanced",
            TargetWorkload = WorkloadClass.Mixed,
            TargetWorkloadType = null,
            PreferredPowerPlan = WindowsPowerPlanKind.Balanced,
            GpuPowerLimitPercent = 100,
            GpuMaxClockMHz = 2484,
            GpuVoltageMv = 1100,
            CpuPptW = 88,
            CpuTdcA = 60,
            CpuEdcA = 90,
            CpuMinFrequencyPercent = 20,
            CpuMaxFrequencyPercent = 100,
            CpuBoostMode = ProcessorBoostMode.Enabled,
            SafetyLimits = new SafetyLimits { MaxCpuTemperatureC = 90, MaxGpuTemperatureC = 85, MaxGpuHotspotTemperatureC = 100 }
        });

        _profiles.Add(new TuningProfile
        {
            Name = "Idle / saver",
            TargetWorkload = WorkloadClass.Idle,
            TargetWorkloadType = WorkloadType.Idle,
            PreferredPowerPlan = WindowsPowerPlanKind.PowerSaver,
            GpuPowerLimitPercent = 50,
            GpuMaxClockMHz = 1200,
            GpuVoltageMv = 862,
            CpuPptW = 45,
            CpuTdcA = 30,
            CpuEdcA = 45,
            CpuMinFrequencyPercent = 5,
            CpuMaxFrequencyPercent = 60,
            CpuBoostMode = ProcessorBoostMode.Disabled,
            SafetyLimits = new SafetyLimits { MaxCpuTemperatureC = 85, MaxGpuTemperatureC = 80, MaxGpuHotspotTemperatureC = 95 }
        });

        _profiles.Add(new TuningProfile
        {
            Name = "Gaming",
            TargetWorkload = WorkloadClass.GpuHeavy,
            TargetWorkloadType = WorkloadType.Gaming,
            PreferredPowerPlan = WindowsPowerPlanKind.HighPerformance,
            GpuPowerLimitPercent = 110,
            GpuMaxClockMHz = 2589,
            GpuVoltageMv = 1150,
            CpuPptW = 105,
            CpuTdcA = 75,
            CpuEdcA = 110,
            CpuMinFrequencyPercent = 30,
            CpuMaxFrequencyPercent = 100,
            CpuBoostMode = ProcessorBoostMode.Aggressive,
            SafetyLimits = new SafetyLimits { MaxCpuTemperatureC = 95, MaxGpuTemperatureC = 90, MaxGpuHotspotTemperatureC = 105 }
        });

        _profiles.Add(new TuningProfile
        {
            Name = "Heavy compute",
            TargetWorkload = WorkloadClass.CpuHeavy,
            TargetWorkloadType = WorkloadType.HeavyCompute,
            PreferredPowerPlan = WindowsPowerPlanKind.HighPerformance,
            GpuPowerLimitPercent = 100,
            GpuMaxClockMHz = 2200,
            GpuVoltageMv = 1075,
            CpuPptW = 142,
            CpuTdcA = 95,
            CpuEdcA = 140,
            CpuMinFrequencyPercent = 20,
            CpuMaxFrequencyPercent = 100,
            CpuBoostMode = ProcessorBoostMode.EfficientAggressive,
            SafetyLimits = new SafetyLimits { MaxCpuTemperatureC = 95, MaxGpuTemperatureC = 88, MaxGpuHotspotTemperatureC = 105 }
        });
    }
}
